# Generated by Django 5.1.3 on 2024-11-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nome', models.TextField(max_length=255)),
                ('Email', models.TextField(max_length=255)),
            ],
        ),
    ]
