# Generated by Django 5.1.3 on 2024-11-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
