# Generated by Django 5.1.3 on 2024-11-07 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caminhao',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Model', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo', to='home.pessoa'),
        ),
        migrations.CreateModel(
            name='Caminhoneiro',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.TextField(max_length=200)),
                ('Email', models.TextField(max_length=100)),
                ('Caminhao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.caminhao')),
            ],
        ),
    ]
