# Generated by Django 5.1.3 on 2024-11-07 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_caminhao_alter_veiculo_pessoa_caminhoneiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caminhoneiro',
            name='Caminhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caminhao', to='home.caminhao'),
        ),
    ]
